sudo: false
language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rake dummy:prepare
  - bundle exec rspec

addons:
  code_climate:
    repo_token: 2446d680d10249420b115f02c97395570e666b3b2e07d7832182b53c52bd4f38
